#!/bin/sh

# BusyBox httpd Startup Script
#

. /etc/rc.d/init.d/functions

LED_SYSFS_PATH="/sys/class/leds/beagleboard\:\:usr1"

case "$1" in
start)
    echo -n "Setting LED permissions: "
    chmod a+w "${LED_SYSFS_PATH}/*"
    check_status
    echo -n "Setting LED initial state: "
    echo "default-on" > "${LED_SYSFS_PATH}"
    check_status
    echo -n "Starting httpd: "
    /usr/sbin/httpd -u www:www -p 80 -h /www -p 0.0.0.0:80
    check_status
    ;;
stop)
    echo -n "Stopping httpd: "
    killall httpd
    check_status
    ;;
restart)
    $0 stop
    $0 start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac