#!/bin/sh

# Wireguard Startup Script
#

. /etc/rc.d/init.d/functions

case "$1" in
start)
    echo -n "Starting Wireguard: "
    /bin/wireguard.sh start
    check_status
    ;;
stop)
    echo -n "Stopping Wireguard: "
    /bin/wireguard.sh stop
    check_status
    ;;
restart)
    $0 stop
    $0 start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac